const libCapacities = [
    {
      "id": 0,
      "name": "Art History/Classics Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Art History/Classics Library",
        "Art History/Classics Library UC Berkeley",
        "Art History/Classics Library Berkeley CA",
        "Art History/Classics Library Berkeley"
      ]
    },
    {
      "id": 1,
      "name": "Bancroft Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Bancroft Library",
        "Bancroft Library UC Berkeley",
        "Bancroft Library Berkeley CA",
        "The Bancroft Library",
        "The Bancroft Library Berkeley",
        "The Bancroft Library UC Berkeley"
      ]
    },
    {
      "id": 2,
      "name": "Berkeley Art Museum and Pacific Film Archive",
      "success": true,
      "matched_search_term": "Berkeley Art Museum and Pacific Film Archive",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            47,
            63,
            80,
            88,
            97,
            96,
            90,
            79,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            94,
            126,
            160,
            176,
            194,
            192,
            180,
            158,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            47,
            63,
            80,
            88,
            97,
            96,
            90,
            79,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            94,
            126,
            160,
            176,
            194,
            192,
            180,
            158,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            47,
            63,
            80,
            88,
            97,
            96,
            90,
            79,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            94,
            126,
            160,
            176,
            194,
            192,
            180,
            158,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            47,
            63,
            80,
            88,
            97,
            96,
            90,
            79,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            94,
            126,
            160,
            176,
            194,
            192,
            180,
            158,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            47,
            63,
            80,
            88,
            97,
            96,
            90,
            79,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            94,
            126,
            160,
            176,
            194,
            192,
            180,
            158,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            47,
            63,
            80,
            88,
            97,
            96,
            90,
            79,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            94,
            126,
            160,
            176,
            194,
            192,
            180,
            158,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            47,
            63,
            80,
            88,
            97,
            96,
            90,
            79,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            94,
            126,
            160,
            176,
            194,
            192,
            180,
            158,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 3,
      "name": "Berkeley Law Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Berkeley Law Library",
        "Berkeley Law Library UC Berkeley",
        "Berkeley Law Library Berkeley CA",
        "Berkeley Law Library Berkeley"
      ]
    },
    {
      "id": 4,
      "name": "Bioscience, Natural Resources & Public Health Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Bioscience, Natural Resources & Public Health Library",
        "Bioscience, Natural Resources & Public Health Library UC Berkeley",
        "Bioscience, Natural Resources & Public Health Library Berkeley CA",
        "Bioscience Natural Resources  Public Health Library University California Berkeley",
        "Bioscience Natural Resources  Public Health Library UC Berkeley",
        "Marian Koshland Bioscience & Natural Resources Library",
        "Marian Koshland Bioscience & Natural Resources Library Berkeley",
        "Marian Koshland Bioscience & Natural Resources Library UC Berkeley"
      ]
    },
    {
      "id": 5,
      "name": "Business Library",
      "success": true,
      "matched_search_term": "Business Library",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            42,
            37,
            28,
            31,
            31,
            37,
            48,
            62,
            68,
            57,
            55,
            53,
            57,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            84,
            74,
            56,
            62,
            62,
            74,
            96,
            124,
            136,
            113,
            110,
            106,
            113,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            42,
            37,
            28,
            31,
            31,
            37,
            48,
            62,
            68,
            57,
            55,
            53,
            57,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            84,
            74,
            56,
            62,
            62,
            74,
            96,
            124,
            136,
            113,
            110,
            106,
            113,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            42,
            37,
            28,
            31,
            31,
            37,
            48,
            62,
            68,
            57,
            55,
            53,
            57,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            84,
            74,
            56,
            62,
            62,
            74,
            96,
            124,
            136,
            113,
            110,
            106,
            113,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            42,
            37,
            28,
            31,
            31,
            37,
            48,
            62,
            68,
            57,
            55,
            53,
            57,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            84,
            74,
            56,
            62,
            62,
            74,
            96,
            124,
            136,
            113,
            110,
            106,
            113,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            42,
            37,
            28,
            31,
            31,
            37,
            48,
            62,
            68,
            57,
            55,
            53,
            57,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            84,
            74,
            56,
            62,
            62,
            74,
            96,
            124,
            136,
            113,
            110,
            106,
            113,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            42,
            37,
            28,
            31,
            31,
            37,
            48,
            62,
            68,
            57,
            55,
            53,
            57,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            84,
            74,
            56,
            62,
            62,
            74,
            96,
            124,
            136,
            113,
            110,
            106,
            113,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            42,
            37,
            28,
            31,
            31,
            37,
            48,
            62,
            68,
            57,
            55,
            53,
            57,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            84,
            74,
            56,
            62,
            62,
            74,
            96,
            124,
            136,
            113,
            110,
            106,
            113,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 6,
      "name": "Chemistry, Astronomy & Physics Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Chemistry, Astronomy & Physics Library",
        "Chemistry, Astronomy & Physics Library UC Berkeley",
        "Chemistry, Astronomy & Physics Library Berkeley CA",
        "Chemistry and Chemical Engineering Library",
        "Chemistry and Chemical Engineering Library Berkeley",
        "Chemistry and Chemical Engineering Library UC Berkeley"
      ]
    },
    {
      "id": 7,
      "name": "Doe Library",
      "success": true,
      "matched_search_term": "Doe Library",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 8,
      "name": "Earth Sciences & Map Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Earth Sciences & Map Library",
        "Earth Sciences & Map Library UC Berkeley",
        "Earth Sciences & Map Library Berkeley CA",
        "Earth Science & Map Library",
        "Earth Science & Map Library Berkeley",
        "Earth Science & Map Library UC Berkeley"
      ]
    },
    {
      "id": 9,
      "name": "East Asian Library",
      "success": true,
      "matched_search_term": "East Asian Library",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            28,
            33,
            49,
            56,
            63,
            68,
            66,
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            56,
            66,
            98,
            112,
            126,
            136,
            132,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            28,
            33,
            49,
            56,
            63,
            68,
            66,
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            56,
            66,
            98,
            112,
            126,
            136,
            132,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            28,
            33,
            49,
            56,
            63,
            68,
            66,
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            56,
            66,
            98,
            112,
            126,
            136,
            132,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            28,
            33,
            49,
            56,
            63,
            68,
            66,
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            56,
            66,
            98,
            112,
            126,
            136,
            132,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            28,
            33,
            49,
            56,
            63,
            68,
            66,
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            56,
            66,
            98,
            112,
            126,
            136,
            132,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            28,
            33,
            49,
            56,
            63,
            68,
            66,
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            56,
            66,
            98,
            112,
            126,
            136,
            132,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            28,
            33,
            49,
            56,
            63,
            68,
            66,
            66,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            56,
            66,
            98,
            112,
            126,
            136,
            132,
            132,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 10,
      "name": "Engineering & Mathematical Sciences Library",
      "success": true,
      "matched_search_term": "Engineering & Mathematical Sciences Library UC Berkeley",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            83,
            95,
            81,
            86,
            67,
            60,
            67,
            60,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            166,
            190,
            162,
            172,
            134,
            120,
            134,
            120,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            83,
            95,
            81,
            86,
            67,
            60,
            67,
            60,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            166,
            190,
            162,
            172,
            134,
            120,
            134,
            120,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            83,
            95,
            81,
            86,
            67,
            60,
            67,
            60,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            166,
            190,
            162,
            172,
            134,
            120,
            134,
            120,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            83,
            95,
            81,
            86,
            67,
            60,
            67,
            60,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            166,
            190,
            162,
            172,
            134,
            120,
            134,
            120,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            83,
            95,
            81,
            86,
            67,
            60,
            67,
            60,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            166,
            190,
            162,
            172,
            134,
            120,
            134,
            120,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            83,
            95,
            81,
            86,
            67,
            60,
            67,
            60,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            166,
            190,
            162,
            172,
            134,
            120,
            134,
            120,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            83,
            95,
            81,
            86,
            67,
            60,
            67,
            60,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            166,
            190,
            162,
            172,
            134,
            120,
            134,
            120,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 11,
      "name": "Environmental Design Archives",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Environmental Design Archives",
        "Environmental Design Archives UC Berkeley",
        "Environmental Design Archives Berkeley CA",
        "College of Environmental Design",
        "College of Environmental Design Berkeley",
        "College of Environmental Design UC Berkeley"
      ]
    },
    {
      "id": 12,
      "name": "Environmental Design Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Environmental Design Library",
        "Environmental Design Library UC Berkeley",
        "Environmental Design Library Berkeley CA",
        "Environmental Design Library University California Berkeley",
        "Environmental Design Library Berkeley"
      ]
    },
    {
      "id": 13,
      "name": "Ethnic Studies Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Ethnic Studies Library",
        "Ethnic Studies Library UC Berkeley",
        "Ethnic Studies Library Berkeley CA",
        "Ethnic Studies Library University California Berkeley",
        "Ethnic Studies Library Berkeley"
      ]
    },
    {
      "id": 14,
      "name": "Graduate Services (study only)",
      "success": true,
      "matched_search_term": "Doe Library University California Berkeley",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 15,
      "name": "Graduate Theological Union Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Graduate Theological Union Library",
        "Graduate Theological Union Library UC Berkeley",
        "Graduate Theological Union Library Berkeley CA",
        "Graduate Theological Union Library University California Berkeley",
        "Graduate Theological Union",
        "Graduate Theological Union Berkeley",
        "Graduate Theological Union UC Berkeley"
      ]
    },
    {
      "id": 16,
      "name": "Institute of Governmental Studies Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Institute of Governmental Studies Library",
        "Institute of Governmental Studies Library UC Berkeley",
        "Institute of Governmental Studies Library Berkeley CA",
        "Institute of Governmental Studies Library University California Berkeley",
        "Institute of Governmental Studies Library Berkeley"
      ]
    },
    {
      "id": 17,
      "name": "Institute of Transportation Studies Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Institute of Transportation Studies Library",
        "Institute of Transportation Studies Library UC Berkeley",
        "Institute of Transportation Studies Library Berkeley CA",
        "Institute of Transportation Studies Library University California Berkeley",
        "Institute of Transportation Studies Library Berkeley"
      ]
    },
    {
      "id": 18,
      "name": "Interlibrary Loan",
      "success": true,
      "matched_search_term": "Doe Library University California Berkeley",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 19,
      "name": "Lawrence Berkeley National Laboratory Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Lawrence Berkeley National Laboratory Library",
        "Lawrence Berkeley National Laboratory Library UC Berkeley",
        "Lawrence Berkeley National Laboratory Library Berkeley CA",
        "Lawrence Berkeley National Laboratory",
        "Lawrence Berkeley National Laboratory Berkeley",
        "Lawrence Berkeley National Laboratory UC Berkeley"
      ]
    },
    {
      "id": 20,
      "name": "Main (Gardner) Stacks",
      "success": true,
      "matched_search_term": "Main (Gardner) Stacks",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            45,
            35,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            62,
            64,
            86,
            62,
            62,
            40,
            40,
            45,
            54,
            37,
            29,
            29,
            48,
            0,
            0
          ],
          "hourly_estimated_count": [
            90,
            70,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            124,
            128,
            172,
            124,
            124,
            80,
            80,
            90,
            108,
            74,
            57,
            57,
            96,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            45,
            35,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            62,
            64,
            86,
            62,
            62,
            40,
            40,
            45,
            54,
            37,
            29,
            29,
            48,
            0,
            0
          ],
          "hourly_estimated_count": [
            90,
            70,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            124,
            128,
            172,
            124,
            124,
            80,
            80,
            90,
            108,
            74,
            57,
            57,
            96,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            45,
            35,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            62,
            64,
            86,
            62,
            62,
            40,
            40,
            45,
            54,
            37,
            29,
            29,
            48,
            0,
            0
          ],
          "hourly_estimated_count": [
            90,
            70,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            124,
            128,
            172,
            124,
            124,
            80,
            80,
            90,
            108,
            74,
            57,
            57,
            96,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            45,
            35,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            62,
            64,
            86,
            62,
            62,
            40,
            40,
            45,
            54,
            37,
            29,
            29,
            48,
            0,
            0
          ],
          "hourly_estimated_count": [
            90,
            70,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            124,
            128,
            172,
            124,
            124,
            80,
            80,
            90,
            108,
            74,
            57,
            57,
            96,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            45,
            35,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            62,
            64,
            86,
            62,
            62,
            40,
            40,
            45,
            54,
            37,
            29,
            29,
            48,
            0,
            0
          ],
          "hourly_estimated_count": [
            90,
            70,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            124,
            128,
            172,
            124,
            124,
            80,
            80,
            90,
            108,
            74,
            57,
            57,
            96,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            45,
            35,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            62,
            64,
            86,
            62,
            62,
            40,
            40,
            45,
            54,
            37,
            29,
            29,
            48,
            0,
            0
          ],
          "hourly_estimated_count": [
            90,
            70,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            124,
            128,
            172,
            124,
            124,
            80,
            80,
            90,
            108,
            74,
            57,
            57,
            96,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            45,
            35,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            62,
            64,
            86,
            62,
            62,
            40,
            40,
            45,
            54,
            37,
            29,
            29,
            48,
            0,
            0
          ],
          "hourly_estimated_count": [
            90,
            70,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            124,
            128,
            172,
            124,
            124,
            80,
            80,
            90,
            108,
            74,
            57,
            57,
            96,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 21,
      "name": "Moffitt Library",
      "success": true,
      "matched_search_term": "Moffitt Library",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            32,
            36,
            48,
            44,
            34,
            34,
            20,
            14,
            10,
            16,
            24,
            34,
            40,
            36,
            34,
            34,
            40,
            38,
            42,
            38,
            38,
            40,
            38,
            30
          ],
          "hourly_estimated_count": [
            64,
            72,
            96,
            88,
            68,
            68,
            40,
            28,
            20,
            32,
            48,
            68,
            80,
            72,
            68,
            68,
            80,
            76,
            84,
            76,
            76,
            80,
            76,
            60
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            32,
            36,
            48,
            44,
            34,
            34,
            20,
            14,
            10,
            16,
            24,
            34,
            40,
            36,
            34,
            34,
            40,
            38,
            42,
            38,
            38,
            40,
            38,
            30
          ],
          "hourly_estimated_count": [
            64,
            72,
            96,
            88,
            68,
            68,
            40,
            28,
            20,
            32,
            48,
            68,
            80,
            72,
            68,
            68,
            80,
            76,
            84,
            76,
            76,
            80,
            76,
            60
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            32,
            36,
            48,
            44,
            34,
            34,
            20,
            14,
            10,
            16,
            24,
            34,
            40,
            36,
            34,
            34,
            40,
            38,
            42,
            38,
            38,
            40,
            38,
            30
          ],
          "hourly_estimated_count": [
            64,
            72,
            96,
            88,
            68,
            68,
            40,
            28,
            20,
            32,
            48,
            68,
            80,
            72,
            68,
            68,
            80,
            76,
            84,
            76,
            76,
            80,
            76,
            60
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            32,
            36,
            48,
            44,
            34,
            34,
            20,
            14,
            10,
            16,
            24,
            34,
            40,
            36,
            34,
            34,
            40,
            38,
            42,
            38,
            38,
            40,
            38,
            30
          ],
          "hourly_estimated_count": [
            64,
            72,
            96,
            88,
            68,
            68,
            40,
            28,
            20,
            32,
            48,
            68,
            80,
            72,
            68,
            68,
            80,
            76,
            84,
            76,
            76,
            80,
            76,
            60
          ]
        },
        "Friday": {
          "hourly_percentages": [
            32,
            36,
            48,
            44,
            34,
            34,
            20,
            14,
            10,
            16,
            24,
            34,
            40,
            36,
            34,
            34,
            40,
            38,
            42,
            38,
            38,
            40,
            38,
            30
          ],
          "hourly_estimated_count": [
            64,
            72,
            96,
            88,
            68,
            68,
            40,
            28,
            20,
            32,
            48,
            68,
            80,
            72,
            68,
            68,
            80,
            76,
            84,
            76,
            76,
            80,
            76,
            60
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            32,
            36,
            48,
            44,
            34,
            34,
            20,
            14,
            10,
            16,
            24,
            34,
            40,
            36,
            34,
            34,
            40,
            38,
            42,
            38,
            38,
            40,
            38,
            30
          ],
          "hourly_estimated_count": [
            64,
            72,
            96,
            88,
            68,
            68,
            40,
            28,
            20,
            32,
            48,
            68,
            80,
            72,
            68,
            68,
            80,
            76,
            84,
            76,
            76,
            80,
            76,
            60
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            32,
            36,
            48,
            44,
            34,
            34,
            20,
            14,
            10,
            16,
            24,
            34,
            40,
            36,
            34,
            34,
            40,
            38,
            42,
            38,
            38,
            40,
            38,
            30
          ],
          "hourly_estimated_count": [
            64,
            72,
            96,
            88,
            68,
            68,
            40,
            28,
            20,
            32,
            48,
            68,
            80,
            72,
            68,
            68,
            80,
            76,
            84,
            76,
            76,
            80,
            76,
            60
          ]
        }
      }
    },
    {
      "id": 22,
      "name": "Morrison Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Morrison Library",
        "Morrison Library UC Berkeley",
        "Morrison Library Berkeley CA",
        "Morrison Library University California Berkeley",
        "Morrison Library Berkeley"
      ]
    },
    {
      "id": 23,
      "name": "Music Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Music Library",
        "Music Library UC Berkeley",
        "Music Library Berkeley CA",
        "Music Library University California Berkeley",
        "Jean Gray Hargrove Music Library",
        "Jean Gray Hargrove Music Library Berkeley",
        "Jean Gray Hargrove Music Library UC Berkeley"
      ]
    },
    {
      "id": 24,
      "name": "Newspapers & Microforms Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Newspapers & Microforms Library",
        "Newspapers & Microforms Library UC Berkeley",
        "Newspapers & Microforms Library Berkeley CA",
        "Newspapers & Microforms Library Berkeley"
      ]
    },
    {
      "id": 25,
      "name": "Privileges Desk",
      "success": true,
      "matched_search_term": "Doe Library University California Berkeley",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 26,
      "name": "Social Research Library",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Social Research Library",
        "Social Research Library UC Berkeley",
        "Social Research Library Berkeley CA",
        "Social Research Library Berkeley"
      ]
    },
    {
      "id": 27,
      "name": "South/Southeast Asia Library (study only)",
      "success": true,
      "matched_search_term": "Doe Library University California Berkeley",
      "max_capacity_baseline": 200,
      "historical_schedule": {
        "Monday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Tuesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Wednesday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Thursday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Friday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Saturday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        },
        "Sunday": {
          "hourly_percentages": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            41,
            52,
            58,
            59,
            62,
            60,
            63,
            67,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ],
          "hourly_estimated_count": [
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            82,
            104,
            115,
            118,
            124,
            120,
            126,
            134,
            0,
            0,
            0,
            0,
            0,
            0,
            0
          ]
        }
      }
    },
    {
      "id": 28,
      "name": "Systemwide Library Facility-North",
      "success": false,
      "error": "No historical popularity data found",
      "search_terms_tried": [
        "Systemwide Library Facility-North",
        "Systemwide Library Facility-North UC Berkeley",
        "Systemwide Library Facility-North Berkeley CA",
        "Northern Regional Library Facility (NRLF)",
        "Northern Regional Library Facility (NRLF) Berkeley",
        "Northern Regional Library Facility (NRLF) UC Berkeley"
      ]
    }
  ]
  
export function getScheduleByName(targetName:string) {
    if (!Array.isArray(libCapacities) || !targetName) return null;

    const library = libCapacities.find(
        (lib) => lib.name?.toLowerCase().trim() === targetName.toLowerCase().trim()
    );

    return library ? library.historical_schedule : null;
}


export function getCurrentDayAndHour() {
  const now = new Date();
  
  return {
    day: now.toLocaleDateString("en-US", { weekday: "long" }),
    hour: now.getHours() // 0 - 23 index matching the hourly array
  };
}

export function getHourlyData(
  targetName: string, 
  day: string, 
  hour: number
) {
  const schedule = getScheduleByName(targetName);
  if (!schedule) return null;

  // Format day string to match keys (e.g., "monday" -> "Monday")
  const formattedDay = day.charAt(0).toUpperCase() + day.slice(1).toLowerCase();
  const dayData = schedule[formattedDay];

  // Validate day exists and hour is within 0–23 range
  if (!dayData || hour < 0 || hour > 23) return null;

  return {
    percentage: dayData.hourly_percentages[hour],
    estimatedCount: dayData.hourly_estimated_count[hour]
  };
}

export function getCurrentHourlyData(targetName: string) {
  const now = new Date();

  // Returns full day name (e.g., "Monday", "Tuesday")
  const currentDay = now.toLocaleDateString("en-US", { weekday: "long" });

  // Returns current hour in 24-hour format (0 - 23)
  const currentHour = now.getHours();

  return getHourlyData(targetName, currentDay, currentHour);
}